# Cloud Build configuration for FastAPI Playground
#
# This configuration uses BuildKit for efficient Docker builds with layer caching.
# The Dockerfile uses BuildKit-specific features (RUN --mount=type=cache,...).
#
# IMPORTANT: Uses the official 'docker' image instead of 'gcr.io/cloud-builders/docker'
# because the latter does not support BuildKit natively.
#
# Usage:
#   - Set up a Cloud Build trigger pointing to this file
#   - Or run manually: gcloud builds submit --config=cloudbuild.yaml
#
# Required substitutions (set via trigger or command line):
#   - _REGION: Cloud Run region (default: europe-west4)
#
# See GCP.md for detailed setup instructions.

substitutions:
  _REGION: 'europe-west4'

steps:
  # Build with BuildKit enabled (required for --mount syntax in Dockerfile)
  - name: 'docker:27'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t gcr.io/$PROJECT_ID/fastapi-playground:$COMMIT_SHA .
    env:
      - 'DOCKER_BUILDKIT=1'

  # Push to Container Registry
  - name: 'docker:27'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-playground:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fastapi-playground'
      - '--image=gcr.io/$PROJECT_ID/fastapi-playground:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--set-env-vars=FIREBASE_PROJECT_ID=$PROJECT_ID,ENVIRONMENT=production,DEBUG=false'

images:
  - 'gcr.io/$PROJECT_ID/fastapi-playground:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
