"""
Reusable OpenAPI response documentation.
"""

from typing import Any

from fastapi.openapi.utils import validation_error_definition
from pydantic import BaseModel

from app.models.error import ProblemResponse, ValidationProblemResponse

type OpenAPIResponse = dict[str, Any]

_REQUEST_ID_HEADER = {
    "description": "Request identifier echoed from the request or generated by the service.",
    "schema": {"type": "string"},
}
_LINK_HEADER = {
    "description": "RFC 8288 links, including schema discovery and pagination where applicable.",
    "schema": {"type": "string"},
}


def response_headers(*, link: bool = False, location: bool = False) -> dict[str, dict[str, Any]]:
    """
    Build headers shared by documented responses.
    """
    headers = {"X-Request-ID": _REQUEST_ID_HEADER}
    if link:
        headers["Link"] = _LINK_HEADER
    if location:
        headers["Location"] = {
            "description": "URI of the created resource.",
            "schema": {"type": "string", "format": "uri-reference"},
        }
    return headers


def success_response(
    description: str,
    schema_name: str,
    *,
    cbor: bool = True,
    location: bool = False,
) -> OpenAPIResponse:
    """
    Document a modeled success response and its response-wide headers.
    """
    response: OpenAPIResponse = {
        "description": description,
        "headers": response_headers(link=True, location=location),
    }
    if cbor:
        response["content"] = {
            "application/cbor": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}},
        }
    return response


def empty_response(description: str) -> OpenAPIResponse:
    """
    Document a response without a representation body.
    """
    return {"description": description, "headers": response_headers()}


def problem_response(
    description: str,
    *,
    model: type[BaseModel] = ProblemResponse,
    authenticate: bool = False,
    retry_after: bool = False,
) -> OpenAPIResponse:
    """
    Document an RFC 9457 response in each supported representation.
    """
    schema = {"$ref": f"#/components/schemas/{model.__name__}"}
    headers = response_headers(link=True)
    if authenticate:
        headers["WWW-Authenticate"] = {
            "description": "Authentication scheme required by the resource.",
            "schema": {"type": "string", "example": "Bearer"},
        }
    if retry_after:
        headers["Retry-After"] = {
            "description": "Seconds to wait before retrying.",
            "schema": {"type": "string", "example": "30"},
        }
    return {
        "description": description,
        "headers": headers,
        "content": {
            "application/problem+json": {"schema": schema},
            "application/problem+cbor": {"schema": schema},
        },
    }


COMMON_CBOR_RESPONSES: dict[int | str, dict[str, Any]] = {
    400: problem_response("Malformed CBOR request"),
    406: problem_response("Requested response format is not supported"),
    413: problem_response("Request body is too large"),
    415: problem_response("Request content type is not supported"),
    500: problem_response("Server error"),
}


def register_schema_components(openapi_schema: dict[str, Any]) -> None:
    """
    Register schemas that are referenced by discovery links but documented inline.
    """
    schemas = openapi_schema.setdefault("components", {}).setdefault("schemas", {})
    for model in (ProblemResponse, ValidationProblemResponse):
        schema = model.model_json_schema(ref_template="#/components/schemas/{model}")
        definitions = schema.pop("$defs", {})
        schemas.update(definitions)
        schemas[model.__name__] = schema
    schemas.setdefault("ValidationError", validation_error_definition)
